mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from accounts import views as accounts_views
from boards.views import BoardListView, TopicListView, PostListView, PostUpdateView
from boards import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', BoardListView.as_view(), name='home'),    # 首页
    url(r'^signup/$', accounts_views.signup, name='signup'),    # 注册
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),   # 登录
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),   # 退出登录
    url(r'^boards/(?P<pk>\d+)/$', TopicListView.as_view(), name='board_topics'),     # 话题
    url(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),   # 添加新话题
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', PostListView.as_view(), name='topic_posts'),   # 帖子列表页
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='reply_topic'),  # 回帖
    # 编辑
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
        PostUpdateView.as_view(), name='edit_post'),

    # 密码修改
    url(r'^reset/$', auth_views.PasswordResetView.as_view(
                                template_name='password_reset.html',
                                email_template_name='password_reset_email.html',
                                subject_template_name='password_reset_subject.txt'),
                                name='password_reset'),    # (重置密码) 邮件正文与主题

    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(
                                template_name='password_reset_done.html'), name='password_reset_done'),

    # 忘记密码
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
                                template_name='password_reset_confirm.html'), name='password_reset_confirm'),

    # 个人中心
    url(r'^settings/account/$', accounts_views.UserUpdateView.as_view(), name='my_account'),

    # 密码修改完成
    url(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
                                template_name='password_reset_complete.html'), name='password_reset_complete'),
    # 修改密码
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(
                                template_name='password_change.html'), name='password_change'),

    # 密码修改完成
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(
                                template_name='password_change_done.html'), name='password_change_done'),


]

apps/boards/forms.py
# -*-coding:utf-8 -*-

from django import forms
from .models import Topic, Post


class NewTopicForm(forms.ModelForm):
    """
    新话题字段
    """
    message = forms.CharField(widget=forms.Textarea(
                              attrs={'rows': 5, 'placeholder': '你在想什么?'}),
                              max_length=4000,
                              help_text='最大长度4000', label="正文")
    # 用来渲染成HTML元素的工具.forms.Textarea对应HTML中的<textarea>标签

    class Meta:
        model = Topic
        fields = ['subject', 'message']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django Boards{% endblock %}</title>
    <link href="{% static 'css/Peralta.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">



    {% block stylesheet %}{% endblock %}

</head>
<body>
    {% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
      <div class="collapse navbar-collapse" id="mainMenu">
          {% if user.is_authenticated %}
              <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {{ user.username }}
                  </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'my_account' %}">个人中心</a>
                <a class="dropdown-item" href="{% url 'password_change' %}">修改密码</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">注销</a>
              </div>
            </li>
          </ul>
         {% else %}
            <form class="form-inline ml-auto">
             <a href="{% url 'login' %}" class="btn btn-outline-secondary">登录</a>
             <a href="{% url 'signup' %}" class="btn btn-primary ml-2">注册</a>
            </form>
          {% endif %}

        </div>
      </div>
    </nav>

    <div class="container">
        <ol class="breadcrumb my-4">
            {% block breadcrumb %}
            {% endblock %}
        </ol>
        {% block context %}
        {% endblock %}
    </div>
    {% endblock body  %}

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block javascript %}{% endblock %}

</body>
</html>

templates/base_accounts.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">Django Boards</a>
    </h1>
    {% block context %}
    {% endblock %}
  </div>
{% endblock %}

templates/edit_post.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Edit post{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">首页</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
  <li class="breadcrumb-item active">编辑提交</li>
{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/simplemde.min.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/simplemde.min.js' %}"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

{% block context %}
  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">保存更改</button>
    <a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">取消</a>
  </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">主页</li>
{% endblock %}

{% block context %}
        <table class="table">
        <thead class="thead-inverse">
          <tr>
            <th>主题</th>
            <th>文章</th>
            <th>话题</th>
            <th>最后提交</th>
          </tr>
        </thead>
        <tbody>
          {% for board in boards %}
            <tr>
              <td>
                  <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
                <small class="text-muted d-block">{{ board.description }}</small>
              </td>
              <td class="align-middle">
                {{ board.get_posts_count }}
              </td>
              <td class="align-middle">
                {{ board.topics.count }}
              </td>
              <td class="align-middle">
                {% with post=board.get_last_post %}
              {% if post %}
              <small>
{#                <a href="{% url 'topic_posts' board.pk topic.pk %}">#}
                  <a href="#">
                  由 {{ post.created_by.username }} 发表于 {{ post.created_at }}
                </a>
              </small>
              {% else %}
                 <small class="text-muted">
                    <em>没有提交</em>
                 </small>
              {% endif %}
                {% endwith %}
          </td>
            </tr>
          {% endfor %}
        </tbody>

      </table>
{% endblock %}

templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}登录{% endblock %}

{% block context %}
    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
          <div class="card-body">
              <h3 class="card-title">登录</h3>
            <form method="post" novalidate>
              {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}">
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">登录</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            创建新用户? <a href="{% url 'signup' %}">注册</a>
          </div>
        </div>
        <div class="text-center py-2">
          <small>
            <a href="#" class="text-muted">忘记密码?</a>
          </small>
        </div>
      </div>
    </div>
{% endblock %}

templates/my_account.html
{% extends 'base.html' %}

{% block title %}个人中心{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">个人中心</li>
{% endblock %}

{% block context %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">保存更改</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/new_topic.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}发布新话题{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">新话题</li>
{% endblock %}

{% block context %}
    <form method="post" novalidate>
  {% csrf_token %}
    {% include 'includes/form.html' %}

{#        {{ form.as_p }}#}

{#        将form有三种渲染选项：form.as_table，form.as_ul，和form.as_p。这是渲染表单所有字段的快速方法。#}
{#        顾名思义，as_table使用表标签来格式化输入，as_ul 创建输入的HTML列表等#}
{#    <div class="form-group">#}
{#        <label for="id_subhect">Subject</label>#}
{#        <input type="text" class="form-control" id="id_subjext" name="subject">#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <label for="id_message">Message</label>#}
{#        <textarea class="form-control" id="id_message" name="message"></textarea>#}
{#    </div>  # 由widget=forms.Textarea()渲染了文本表单#}
    <button type="submit" class="btn btn-success">提交</button>
    </form>
{% endblock %}

templates/password_change.html
{% extends 'base.html' %}

{% block title %}修改密码{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">修改密码</li>
{% endblock %}

{% block context %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">修改密码</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/password_reset.html
{% extends 'base_accounts.html' %}

{% block title %}密码重置{% endblock %}

{% block context %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">密码重置</h3>
          <p>输入您的邮箱地址，我们将发送一个链接重置您的密码。</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">点击发送邮件</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_confirm.html
{% extends 'base_accounts.html' %}

{% block title %}
  {% if validlink %}
    {{ form.user.username }} 密码重置
  {% else %}
    重新设置您的密码
  {% endif %}
{% endblock %}

{% block context %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">更改密码 @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">密码重置</button>
            </form>
          {% else %}
            <h3 class="card-title">重置您的密码</h3>
            <div class="alert alert-danger" role="alert">
              看起来你点击了无效的密码重置链接。请再试一次。
            </div>
            <a href="{% url 'password_reset' %}" class="btn btn-secondary btn-block">请求一个新的密码重置链接。</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_done.html
{% extends 'base_accounts.html' %}

{% block title %}密码重置{% endblock %}

{% block context %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">重置您的密码</h3>
          <p>检查您的电子邮件的链接，以重置您的密码。如果它在几分钟之内没有出现，请检查是否在您的垃圾邮箱.</p>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">返回登录</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/record.html
{% load  widget_tweaks %}
{% render_field field class="form-control" %}

render_field模板标签的一些示例：
{% render_field form.subject class="form-control" %}
{% render_field form.message class="form-control" placeholder=form.message.label %}
{% render_field field class="form-control" placeholder="Write a message!" %}
{% render_field field style="font-size: 20px" %}



三种不同的渲染状态：

初始状态：表单没有数据（没有绑定）
无效的：我们添加.is-invalidCSS类，并添加错误消息在一个类的元素 .invalid-feedback。表单域和消息呈现为红色。
有效：我们添加.is-validCSS类以便将表单字段以绿色绘制，并向用户反馈此字段是否合适。

{% include 'includes/form.html' %} 用来在另一个模板中包含 HTML模板。

templates/signup.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
     <div class="container">
         <h1 class="text-center logo my-4">
             <a href="{% url 'home' %}">Django Boards</a>
         </h1>
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10 col-sm-12">
                <div class="card">
                    <div class="card-body">
            <h3 class="card-title">注册</h3>
     <form method="post" novalidate>
         {% csrf_token %}
         {% include 'includes/form.html' %}
         <button type="submit" class="btn btn-primary">创建一个账户</button>
     </form>
     </div>
        <div class="card-footer text-muted text-center">
           已经注册? <a href="{% url 'login' %}">点击登录</a>
           </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/topic_posts.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load gravatar %}
{% block title %}{{ topic.subject }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">首页</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block context %}
  <div class="mb-4">
    <a href="{% url 'reply_topic' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">回复</a>
  </div>

  {% for post in posts %}
    <div id="{{ post.pk }}" class="card {% if forloop.last %}mb-4{% else %}mb-2{% endif %} {% if forloop.first %}border-dark{% endif %}">
         {% if forloop.first %}
             <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
         {% endif %}
      <div class="card-body p-3">
        <div class="row">
          <div class="col-2">
            <img src="{{ post.created_by|gravatar }}" alt="{{ post.created_by.username }}" class="w-100">
            <small>发帖数: {{ post.created_by.posts.count }}</small>
          </div>
          <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
                <small class="text-muted">{{ post.created_at }}</small>
              </div>
            </div>
            {{ post.get_message_as_markdown }}
            {% if post.created_by == user %}
              <div class="mt-3">
                <a href="{% url 'edit_post' post.topic.board.pk post.topic.pk post.pk %}"
                   class="btn btn-primary btn-sm" role="button">编辑</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
    {% include 'includes/pagination.html' %}
{% endblock %}